apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-app-2
  labels:
    name: despliegue-app-2
    app: testing-kube-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: testing-kube-pod-2
      app: testing-kube-app-2
  template:
    metadata:
      name: testing-kube-pod-2
      labels:
        name: testing-kube-pod-2
        app: testing-kube-app-2
    spec:
      containers:
        - name: testing-kube-container-app2
          image: "615491348215.dkr.ecr.us-east-1.amazonaws.com/testingeks-app2:latest"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          livenessProbe:
            httpGet:
              path: /estoyvivo
              port: 4500
            initialDelaySeconds: 5
            periodSeconds: 5